### ISSUE TITLE
R has to be restarted

### ISSUE THREAD

**Issue by GoChartingAdmin** [jimhester/archive#11] opened 2017-08-15 11:23 UTC
I have a winrar file which is a group of 7 csv files.  In the below code, if I run one file at a time, it works but when I use a "For Loop" against the set of 7 files, R gets hanged and has to be restarted

Code:

```
library(archive)
library(readr)
setwd("C:/Users/debsush/Documents/IEOD/")

EOD <- data.frame(matrix(NA, nrow = 1, ncol = 11),stringsAsFactors = FALSE)
colnames(EOD) <- c("TICKER","NAME","PRODUCT","EXCHANGE","DATE","OPEN","HIGH","LOW","CLOSE","VOLUME","IO")
#Remove all NA rows from GStocksFinancials
EOD<- EOD[which(!is.na(EOD$TICKER)), ]
#Process Data
doclist = list.files()
archive <- archive(doclist[[1]])
arcFile=NULL
for (counter in 1:6){
  fileName = toupper(archive$path[counter])
  if (length(grep(".CSV",fileName))>0 && grep(".CSV",fileName)==1) {
    
    if (length(grep("BSE",fileName))>0 && grep("BSE",fileName)==1){
      exchange="BSE"
    } else {
      exchange ="NSE"
    }
    
    if (length(grep("INDICES",fileName))>0 && grep("INDICES",fileName)==1){
      product="EQINDEX"
    } else if (length(grep("OPTIONS",fileName))>0 && grep("OPTIONS",fileName)==1){
      product="OPTIONS"
    } else if (length(grep("FOREX",fileName))>0 && grep("FOREX",fileName)==1){
      product ="FOREXFUT"
    } else if (length(grep("FUT",fileName))>0 && grep("FUT",fileName)==1){
      product ="EQFUT"
    } else {
      product ="EQCASH"
    }
    arcFile = archive_read(archive,archive$path[counter])
    file=read_csv(arcFile,col_type=cols())
    arcFile=NULL
    cat(counter)
    file$exchange=exchange
    file$product=product
    colnames(file)=c("TICKER","NAME","DATE","OPEN","HIGH","LOW","CLOSE","VOLUME","IO","EXCHANGE","PRODUCT")
    file=file[,c("TICKER","NAME","PRODUCT","EXCHANGE","DATE","OPEN","HIGH","LOW","CLOSE","VOLUME","IO")]
    EOD = rbind(EOD,file)
  }
}
```

I am not sure if it an issue with archive or readr.  The behavior is very random and unpredictable. 

PS: I can share the winrar file if that helps.  Github does not allow attaching winrar files so I would have to email you.

Regards
SD

**Comment by jimhester** [comment] 2017-08-15 15:49
I can't tell from this example what is wrong. You should try reading the files with `utils::read.csv()` to remove readr from the equation.

If you are able to reproduce this consistently please try to create a [minimal reproducible example](http://www.tidyverse.org/help/) that illustrates the problem.

I cannot do anything to fix the issue without data and something I can reproduce on my machine.

**Comment by GoChartingAdmin** [comment] 2017-08-16 01:02
Please see the reprex code below

```
library(reprex)
library(archive)
library(readr)
setwd("~/IEOD/")  # Mention the path where you place the rar file
archive <- archive("EOD20170814.rar")
arcFile=NULL
for (counter in 1:NROW(archive)){
    arcFile = archive_read(archive,archive$path[counter])
    file=read_csv(arcFile,col_type=cols())
    arcFile=NULL
    cat(paste("Success Loop Number:",counter,sep=""))
}
```
In my machine, I am finding R gets hanged after a couple of loops.  You may find success in your first attempt but if you repeat the same code a couple of twice, you will be able to see that eventually it may need restarting R.  I fear that all the connections may not be "open" when the code is trying to read from the files in a loop leading to the issue.  Please suggest best practices to ensure all connections are open when readr is trying to read the files and when should we close the connections.

Please let me know the email ID where I can send the file "EOD20170814.rar"

Regards

**Comment by jimhester** [comment] 2017-08-16 10:09
james.f.hester@gmail.com

**Comment by jimhester** [comment] 2017-08-16 12:46
Sorry I cannot reproduce the issue, what version of **archive** are you using and what version of libarchive is it linked against? Please be sure you are using the latest version of **archive**.

```r
devtools::session_info()
archive:::libarchive_version()
```

Reading files from the file 10000 times produced no issues on my machine, with the following
```r
library(archive)
library(readr)
archive <- archive("EOD20170814.rar")
for (i in 0:10000){
  file <- read_csv(archive::archive_read(archive, (i %% length(archive)) + 1), col_type=cols())
  cat("\r", i)
}
```

**Comment by GoChartingAdmin** [comment] 2017-08-16 13:18
> devtools::session_info()
Session info ------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, mingw32             
 ui       RStudio (0.99.893)          
 language (EN)                        
 collate  English_United States.1252  
 tz       Europe/Paris                
 date     2017-08-16                  

Packages ----------------------------------------------------------------------------------------------------------------
 package  * version date       source        
 devtools   1.12.0  2016-06-24 CRAN (R 3.3.2)
 digest     0.6.9   2016-01-08 CRAN (R 3.3.1)
 memoise    1.0.0   2016-01-29 CRAN (R 3.3.2)
 withr      1.0.2   2016-06-20 CRAN (R 3.3.2)

archive:::libarchive_version()
[1] ‘3.2.2’

**Comment by jimhester** [comment] 2017-08-16 13:37
You need to load the **archive** and **readr** packages first before running `devtools::session_info()`.

**Comment by GoChartingAdmin** [comment] 2017-08-16 14:07
I am sorry.

> devtools::session_info()
Session info ------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, mingw32             
 ui       RStudio (0.99.893)          
 language (EN)                        
 collate  English_United States.1252  
 tz       Europe/Paris                
 date     2017-08-16                  

Packages ----------------------------------------------------------------------------------------------------------------
 package    * version date       source                            
 archive    * 1.0.0   2017-08-11 Github (jimhester/archive@a203312)
 devtools     1.12.0  2016-06-24 CRAN (R 3.3.2)                    
 digest       0.6.9   2016-01-08 CRAN (R 3.3.1)                    
 hms          0.3     2016-11-22 CRAN (R 3.3.2)                    
 memoise      1.0.0   2016-01-29 CRAN (R 3.3.2)                    
 R6           2.1.2   2016-01-26 CRAN (R 3.3.1)                    
 Rcpp         0.12.12 2017-07-15 CRAN (R 3.3.3)                    
 readr      * 1.1.1   2017-05-16 CRAN (R 3.3.3)                    
 rlang        0.1.2   2017-08-09 CRAN (R 3.3.3)                    
 rstudioapi   0.6     2016-06-27 CRAN (R 3.3.2)                    
 tibble       1.3.3   2017-05-28 CRAN (R 3.3.3)                    
 withr        1.0.2   2016-06-20 CRAN (R 3.3.2)                    
> archive:::libarchive_version()
[1] ‘3.2.2’

**Comment by GoChartingAdmin** [comment] 2017-08-18 18:36
I have today tried the same code in another computer with latest versions of R and dependent packages involved.  The result is still the same.  The R sessions gets hanged and I have to restart the R session.

In both my cases, I am using Windows OS.  Can this be the reason why it is failing at my end?

> devtools::session_info()
Session info -------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 system   x86_64, mingw32             
 ui       RStudio (0.99.491)          
 language (EN)                        
 collate  English_United States.1252  
 tz       Europe/Berlin               
 date     2017-08-18                  

Packages -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 package   * version date       source                            
 archive   * 1.0.0   2017-08-18 Github (jimhester/archive@a203312)
 base      * 3.4.1   2017-06-30 local                             
 base64enc   0.1-3   2015-07-28 CRAN (R 3.4.1)                    
 compiler    3.4.1   2017-06-30 local                             
 datasets  * 3.4.1   2017-06-30 local                             
 DBI       * 0.7     2017-06-18 CRAN (R 3.4.1)                    
 devtools    1.13.3  2017-08-02 CRAN (R 3.4.1)                    
 digest      0.6.12  2017-01-27 CRAN (R 3.4.1)                    
 gmailr    * 0.7.1   2016-04-12 CRAN (R 3.4.1)                    
 graphics  * 3.4.1   2017-06-30 local                             
 grDevices * 3.4.1   2017-06-30 local                             
 hms         0.3     2016-11-22 CRAN (R 3.4.1)                    
 httr        1.3.0   2017-08-16 CRAN (R 3.4.1)                    
 magrittr    1.5     2014-11-22 CRAN (R 3.4.1)                    
 memoise     1.1.0   2017-04-21 CRAN (R 3.4.1)                    
 methods   * 3.4.1   2017-06-30 local                             
 R6          2.2.2   2017-06-17 CRAN (R 3.4.1)                    
 Rcpp        0.12.12 2017-07-15 CRAN (R 3.4.1)                    
 readr     * 1.1.1   2017-05-16 CRAN (R 3.4.1)                    
 rlang       0.1.2   2017-08-09 CRAN (R 3.4.1)                    
 RMySQL    * 0.10.13 2017-08-14 CRAN (R 3.4.1)                    
 stats     * 3.4.1   2017-06-30 local                             
 tibble      1.3.3   2017-05-28 CRAN (R 3.4.1)                    
 tools       3.4.1   2017-06-30 local                             
 utils     * 3.4.1   2017-06-30 local                             
 withr       2.0.0   2017-07-28 CRAN (R 3.4.1)                    
> archive:::libarchive_version()
[1] ‘3.2.2’

**Comment by GoChartingAdmin** [comment] 2017-08-18 21:04
I have also tried the same in AWS EC2 and results are somewhat better (program completed without any hiccups in 5/10 times) but overall the loop does terminate the R session

**Comment by GoChartingAdmin** [comment] 2017-08-19 12:51
Today, I tried to run the code on a winrar folder containing 1000+ files each of ~30 KB and the code executed successfully looping through the files and reading them happily.  This makes me believe that the issue is related to file size and not related to OS or R package versions in my case.  The loop gets hanged when it comes across a heavy file of the tune of ~350KB. Appreciate your thoughts

**Comment by GoChartingAdmin** [comment] 2017-10-16 17:55
Any update on this

**Comment by jimhester** [comment] 2021-06-09 17:26
As we never were able to successfully reproduce this I will close the issue.

I am sure there is some real problem with the current code, but without being able to reproduce it I don't have a good way to find it.

**Closed by jimhester** 2021-06-09 17:26 UTC
Labels: reprex
